//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amortyzacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int IdAccount { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public int Permission { get; set; }
        public int Workers_IdWorker { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
