//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amortyzacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amortizations
    {
        public int IdAmortization { get; set; }
        public string Type { get; set; }
        public double AmortizationAmount { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Hardware_IdHardware { get; set; }
    
        public virtual Hardware Hardware { get; set; }
    }
}
