//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amortyzacja
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IODatabaseEntities : DbContext
    {
        public IODatabaseEntities()
            : base("name=IODatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amortizations> Amortizations { get; set; }
        public virtual DbSet<Employment> Employment { get; set; }
        public virtual DbSet<Hardware> Hardware { get; set; }
        public virtual DbSet<Licenses> Licenses { get; set; }
        public virtual DbSet<Purchases> Purchases { get; set; }
        public virtual DbSet<Software> Software { get; set; }
        public virtual DbSet<Subscriptions> Subscriptions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
