//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amortyzacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public int IdSoftware { get; set; }
        public string SoftwareType { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> Workers_IdWorker { get; set; }
        public Nullable<int> Licenses_IdLicense { get; set; }
        public Nullable<int> Subscriptions_IdSubscription { get; set; }
    
        public virtual License License { get; set; }
        public virtual Subscription Subscription { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
